### PR TITLE
Fixes #29 Style selection in layer properties doesn't display options

### LINKED ISSUE #29: Style selection in layer properties doesn't display options
to reproduce:
- Open a map and add a layer (QUARTIERI) from the catalog
- select the layer and open the properties/settings modal
- click on style tab
- open select input
- options are visible
- close the properties/settings modal
- open the properties/settings modal again
- click on style tab
- open select input
- options are not visible

### PR DESCRIPTION
**Pull request by allyoucanmap**
Fix #29

### CODE REVIEW

File: js/utils/ProjectUtils.js [hunk 1]
```diff
@@ -56,6 +61,23 @@ const ProjectUtils = {
...
         return style;
+    },
+    formatAvailableStyles: availableStyles => {
+        if (!availableStyles) {
+            return null;
+        }
+        if (isArray(availableStyles) && availableStyles.length === 0) {
+            return null;
+        }
+        return head(availableStyles.filter(style => head(Object.keys(style).filter(key => key === 'name')))) ?
```
Comment (offtherailz) [inline js/utils/ProjectUtils.js]: `head(Object.keys(style).filter(key => key === 'name'))` --> `style && style.name`
