### PR TITLE
Fixed #21 localized style is loaded based on the current locale selected

### LINKED ISSUE #21: Loading of localized style is not aligned with the selected lang
## Steps to reproduce:

- open a map
- save it with a localized style different from the browser language
- go to the home
- load the saved map
the localized style used should be aligned with the language of MapStore2 (if available, default one otherwise)

### PR DESCRIPTION
**Pull request by MV88**
Now it checks for the localized style when a map is opened (map config loaded), or when the locale is changed

### CODE REVIEW

File: js/epics/__tests__/locale-test.js [hunk 1]
```diff
@@ -0,0 +1,237 @@
...
+          bounds: {
+            minx: '11.274139788331421',
+            miny: '46.44238098464227',
+            maxx: '11.434390795696103',
+            maxy: '46.53194067237907'
+          }
+        },
+        visibility: true,
+        singleTile: false,
+        allowedSRS: {
```
Comment (offtherailz) [inline js/epics/__tests__/locale-test.js]: remove everything is not required for the test
