### PR TITLE
Fixed #22 search selected languages

### LINKED ISSUE #22: Search with german language not working
## Steps to reproduce
- open a map
- select german language
- perform a search with the text "romstrasse"

## Result 
no result is returned

## Expected result
it should return some results romstrasse etc..

### PR DESCRIPTION
**Pull request by MV88**
Fixed #22

### CODE REVIEW

File: js/epics/search.js [hunk 1]
```diff
@@ -10,20 +10,28 @@ const {API} = require('../../MapStore2/web/client/api/searchText');
...
 const Rx = require('rxjs');
 const {LOCAL_CONFIG_LOADED} = require('../../MapStore2/web/client/actions/localConfig');
+const {currentLocaleSelector} = require('../../MapStore2/web/client/selectors/locale');
+const {head} = require('lodash');
+
 const axios = require('axios');
 const urlUtil = require('url');
 
-const registerSearchServiceEpic = action$ => action$.ofType(LOCAL_CONFIG_LOADED).switchMap(() => {
+const getActualLang = (state, lang) => head(currentLocaleSelector(state).split('-')) || lang || "en";
```
Comment (offtherailz) [inline js/epics/search.js]: the default should be de or it, because this service does not have "en"
